name: Build AIM Meta-Design App
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # --- New Steps to Prepare Web Assets ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: www/package.json

      - name: Install Web Dependencies
        run: npm install
        working-directory: ./www

      - name: Sync Capacitor Assets
        # This command copies your web code (www) into the native Android project.
        run: npx cap sync android
        working-directory: ./www
      # --- End of New Steps ---

      - name: Build Android App with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: android
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aim-metadesign-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
