# ... (existing workflow preamble)

jobs:
  build:
    runs-on: ubuntu-latest # Or your specified runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for gradlew to function properly

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Debug - List Android directory contents and permissions
        run: |
          ls -la android/
          ls -la android/gradle/wrapper/
          # Ensure gradlew has executable permissions
          chmod +x android/gradlew
        # This will show if gradlew, gradlew.bat, and the gradle/wrapper folder exist, and their permissions.

      - name: Debug - Show gradle-wrapper.properties content
        run: cat android/gradle/wrapper/gradle-wrapper.properties
        # This confirms the content of the properties file as seen by the runner.

      - name: Debug - Check which Java is being used
        run: |
          java -version
          which java
        # Confirms JDK setup.

      - name: Debug - Attempt to run gradlew version
        run: |
          cd android
          ./gradlew --version # This should show the version of Gradle that gradlew actually uses
        # This is CRITICAL. It will reveal if gradlew is being executed and which Gradle version it resolves.

      - name: Build Android App with Gradle
        run: |
          cd android
          ./gradlew clean assembleDebug
        # Your actual build command
