name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Show gradle-wrapper.properties
        run: cat android/gradle/wrapper/gradle-wrapper.properties

      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      - name: Validate Gradle wrapper URL
        run: |
          URL=$(grep distributionUrl= android/gradle/wrapper/gradle-wrapper.properties | cut -d'=' -f2- | tr -d '\r' | xargs)
          echo "Using Gradle distribution: '$URL'"
          curl -I "$URL"

      - name: Run Gradle build
        run: |
          cd android
          ./gradlew clean assembleDebug --stacktrace --no-daemon
