name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    # Sets the default working directory for all run steps in this job
    defaults:
      run:
        working-directory: ./www

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          # Point caching to the correct package.json
          cache-dependency-path: www/package.json

      - name: Install dependencies
        # Using npm install because no package-lock.json is available
        run: npm install

      - name: Lint source code
        run: npm run lint

      - name: Run test script
        run: npm test
