name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    # The 'defaults' block has been removed to fix the pathing issue.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          # This path is now resolved correctly from the repository root.
          cache-dependency-path: www/package.json

      - name: Install dependencies
        run: npm install
        working-directory: ./www

      - name: Lint source code
        run: npm run lint
        working-directory: ./www

      - name: Run test script
        run: npm test
        working-directory: ./www
