name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./www

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: www/package.json

      - name: Install dependencies
        run: npm install

      - name: Lint source code
        run: npm run lint

      # The 'test' and 'build'/'upload' steps are removed as per the recommendation
      # to ensure the workflow passes without defined tests or a build directory.
